[package]
name = "distributed-gradient"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rufi_core = "15.1.1"
rufi_gradient = "1.0.0"
commons = { path = "../commons" }